---
title: "131_HW6"
author: "Zack Reardon"
date: "11/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(tidymodels)
library(ggplot2)
library(glmnet)
# installing and loading janitor package
library(janitor)
library(pROC)
library(corrplot)
tidymodels_prefer()
```

Exercise 1

```{r}
# reading in the data
pokemon <- read_csv("/Users/zackreardon/Downloads/homework-6/data/Pokemon.csv")

# cleaning names
pokemon <- clean_names(pokemon)

# filtering out rarer types
pokemon <- filter(pokemon, type_1 %in% c("Bug", "Fire", "Grass", "Normal", "Water", "Psychic"))

# converting type_1 and legendary to factors
pokemon$type_1 <- as.factor(pokemon$type_1)
pokemon$legendary <- as.factor(pokemon$legendary)

# do initial split of data
pokemon_split <- initial_split(pokemon, prop=0.8, strata=type_1)

pokemon_train <- training(pokemon_split)
pokemon_test <- testing(pokemon_split)

# fold training set with v=5 and stratify on outcome
pokemon_folds <- vfold_cv(pokemon_train, v=5, strata=type_1)

# create recipe
pokemon_recipe <- recipe(type_1 ~ legendary + generation + sp_atk + attack + speed + defense + hp + sp_def, data=pokemon_train) %>%
  # dummy coding categorical predictors
  step_dummy(legendary, generation) %>%
  # centering and scaling all predictors
  step_center(all_predictors()) %>%
  step_scale(all_predictors())
```

Exercise 2

```{r}
# creating correlation plot of numeric predictors
pokemon_train %>%
  select(where(is.numeric), -number) %>%
  cor() %>%
  corrplot()
```

Exercise 3

Exercise 4

Exercise 5

Exercise 6

Exercise 7

Exercise 8

Exercise 9

Exercise 10